name: build holochain
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  holochain-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - arch: macos-x86_64
            runs-on: [macos-latest]
          - arch: macos-arm64
            runs-on: [self-hosted, macOS, ARM64]
          - arch: linux-x86_64
            runs-on: [ubuntu-latest]
        cachixName:
          - holochain-ci
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: "Displays Xcode current version"
        run: |
          sudo xcode-select -p || :

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: false

      - name: Install nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command
        if: "${{ matrix.platform.arch != 'macos-arm64' }}"

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        if: "${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}"
        with:
          name: "${{ matrix.cachixName }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build derivations
        env:
          nix_attribute: "${{ matrix.nixAttribute }}"
        run: nix build .#holochain -L --no-link
